<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:
1. - Data Latih adalah data yang digunakan untuk training model
   - Data Validation digunakan untuk proses validasi model dan mencegah overfitting.
   - Data Testing, digunakan untuk testing model, sebagai simulasi penggunaan model pada dunia nyata. Data testing tidak boleh pernah dilihat oleh model sebelumnya.
2. Performa model yang bagus adalah model yang dapat memprediksi suatu data yang belum pernah diliat sebelumnya dengan tepat. 
3. Confusion matrix juga sering disebut error matrix. Pada dasarnya confusion matrix memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh sistem (model) dengan hasil klasifikasi sebenarnya. Confusion matrix berbentuk tabel matriks yang menggambarkan kinerja model klasifikasi pada serangkaian data uji yang nilai sebenarnya diketahui. 
4. Classification Report adalah fungsi dari sklearn yang berguna untuk memvisualisasikan hasil Confussion Matrix berupa Precission, Recall, F1-Score

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [2]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [3]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [8]:
#Membagi data feature dan data target
x = df.drop('survival_status', axis=1)
y = df['survival_status']

In [43]:
# Code here
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, classification_report

x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.25, random_state=50, stratify=y)


In [35]:
model_knn = KNeighborsClassifier(n_neighbors=3)

In [36]:
model_knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [37]:
cv_result = cross_val_score(model_knn, x, y, cv=5,  scoring='roc_auc')


In [38]:
cv_result

array([0.70261438, 0.55277778, 0.63888889, 0.67916667, 0.60694444])

In [39]:
#Rata rata hasil Cross Validation
print(cv_result.mean())

0.6360784313725489


In [41]:
#Prediksi data test dengan model yang telah dibuat
y_predict = model_knn.predict(x_test)
print(y_predict)

[1 2 2 1 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 2 1 1
 2 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 1 1 1 2 2
 1 1 1]


In [59]:
#hasil confusion matrix
confusion_matrix(y_test, y_predict, labels=[1, 2])

array([[49,  8],
       [12,  8]], dtype=int64)

In [54]:
#hasil clasification report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           1       0.80      0.86      0.83        57
           2       0.50      0.40      0.44        20

    accuracy                           0.74        77
   macro avg       0.65      0.63      0.64        77
weighted avg       0.72      0.74      0.73        77



In [68]:
TP = 49
FN = 8
FP = 12
TN = 8

print('Data Posiif')
precision = TP/(TP+FP)
print(f'Precision : ',precision)
recall = TP/(TP+FN)
print(f'Precision : ',recall)
f1score = 2*precision*recall/(precision+recall)
print(f'F1-Score  :',f1score)
print('')
print('Data Negatif')
precisionN = TN/(TN+FN)
print(f'Precision : ',precisionN)
recallN = TN/(TN+FP)
print(f'Precision : ',recallN)
f1scoreN = 2*precisionN*recallN/(precisionN+recallN)
print(f'F1-Score  :',f1scoreN)

Data Posiif
Precision :  0.8032786885245902
Precision :  0.8596491228070176
F1-Score  : 0.8305084745762712

Data Negatif
Precision :  0.5
Precision :  0.4
F1-Score  : 0.4444444444444445


---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:
1. - Bias adalah error yang diseabkan karena pengggunaan model yang terlalu simple sehingga tidak dapat memprediksi dengan baik
   - Variance adalah error yang disebabkan dikarenakan model yang terlalu fit ke data latih dan mempelajari terlalu dalam sehingga jika terdapat data testing akan sulit untuk memprediksi dengan benar
2. - Overfitting adalah suatu keadaan dimana data yang digunakan untuk pelatihan itu adalah yang "terbaik". Sehingga apabila dilakukan tes dengan menggunakan data yang berbeda dapat mengurangi akurasi 
   - Underfitting adalah keadaan dimana model pelatihan data yang dibuat tidak mewakilkan keseluruhan data yang akan digunakan nantinya.
3. Untuk melalukan kompleksitas model harus mempertimbangkan bentuk data terlebih dahulu yang mana data tersebut data simple atau komplek, data tersebut balance atau imbalance, dan juga memperhatikan kelengkapan data dan noise yang ada
4. Model yang baik adalah model yang memiliki titik tengah antara Bias dan Variance sehingga model tidak terlalu simple dan tidak terlalu fit ke data training
5. - GridSeachCV digunakan saat data yang diambil tidak terlalu banyak noise dan simple dikarenakan semua data akan di search kombinasinya sehingga memakan waktu dan performa
   - RandomizedSearchCV bekerja paling baik untuk data dimensi yang lebih rendah karena waktu yang dibutuhkan untuk menemukan set yang tepat lebih sedikit dengan jumlah iterasi yang lebih sedikit

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [72]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [73]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [74]:
x = df.drop('survival_status', axis=1)
y = df['survival_status']

In [98]:
# Code here
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer

x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.25, random_state=50, stratify=y)
model = KNeighborsClassifier(n_neighbors=3)
param_grid = {'n_neighbors':np.arange(3, 60), 'weights':['distance', 'uniform']}
gscv = GridSearchCV(model, param_grid=param_grid, scoring='roc_auc', cv=5)
gscv.fit(x_train, y_train)


GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'n_neighbors': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59]),
                         'weights': ['distance', 'uniform']},
             scoring='roc_auc')

In [99]:
print(f'Hyperparameter terbaik : ',gscv.best_params_)
print(f'Score validasi terbaik : ',gscv.best_score_)

Hyperparameter terbaik :  {'n_neighbors': 22, 'weights': 'uniform'}
Score validasi terbaik :  0.7021476072946661


In [100]:
hasil_proba = gscv.predict_proba(x_test)
print(hasil_proba)

[[0.72727273 0.27272727]
 [0.77272727 0.22727273]
 [0.5        0.5       ]
 [0.77272727 0.22727273]
 [0.40909091 0.59090909]
 [0.45454545 0.54545455]
 [0.81818182 0.18181818]
 [0.90909091 0.09090909]
 [0.95454545 0.04545455]
 [0.86363636 0.13636364]
 [0.40909091 0.59090909]
 [0.81818182 0.18181818]
 [0.59090909 0.40909091]
 [0.40909091 0.59090909]
 [0.81818182 0.18181818]
 [0.90909091 0.09090909]
 [0.95454545 0.04545455]
 [0.95454545 0.04545455]
 [0.81818182 0.18181818]
 [0.63636364 0.36363636]
 [0.86363636 0.13636364]
 [0.81818182 0.18181818]
 [0.72727273 0.27272727]
 [0.86363636 0.13636364]
 [0.77272727 0.22727273]
 [0.72727273 0.27272727]
 [0.31818182 0.68181818]
 [0.90909091 0.09090909]
 [0.40909091 0.59090909]
 [0.90909091 0.09090909]
 [0.86363636 0.13636364]
 [0.77272727 0.22727273]
 [0.77272727 0.22727273]
 [0.86363636 0.13636364]
 [0.81818182 0.18181818]
 [0.86363636 0.13636364]
 [0.63636364 0.36363636]
 [0.5        0.5       ]
 [0.90909091 0.09090909]
 [0.81818182 0.18181818]


In [102]:
gscv.classes_

array([1, 2], dtype=int64)

In [112]:
positif_die_5_year = hasil_proba[:,1]
print(positif_die_5_year)

[0.27272727 0.22727273 0.5        0.22727273 0.59090909 0.54545455
 0.18181818 0.09090909 0.04545455 0.13636364 0.59090909 0.18181818
 0.40909091 0.59090909 0.18181818 0.09090909 0.04545455 0.04545455
 0.18181818 0.36363636 0.13636364 0.18181818 0.27272727 0.13636364
 0.22727273 0.27272727 0.68181818 0.09090909 0.59090909 0.09090909
 0.13636364 0.22727273 0.22727273 0.13636364 0.18181818 0.13636364
 0.36363636 0.5        0.09090909 0.18181818 0.13636364 0.09090909
 0.18181818 0.31818182 0.27272727 0.09090909 0.5        0.18181818
 0.18181818 0.18181818 0.13636364 0.13636364 0.54545455 0.36363636
 0.22727273 0.13636364 0.04545455 0.18181818 0.09090909 0.18181818
 0.59090909 0.18181818 0.18181818 0.40909091 0.09090909 0.09090909
 0.09090909 0.27272727 0.31818182 0.22727273 0.13636364 0.18181818
 0.27272727 0.18181818 0.18181818 0.13636364 0.22727273]


In [128]:
from sklearn.metrics import roc_auc_score

model.fit(x_train, y_train)
y_predik = model.predict(x_test)

score_roc_auc = roc_auc_score(y_test, y_predik)
print('Score ROC_AUC (KNN) : ', score_roc_auc)

Score ROC_AUC (KNN) :  0.6298245614035087


In [125]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV


dtc = DecisionTreeClassifier()
params = {'max_leaf_nodes': list(range(2, 100)), 'min_samples_split': [2, 3, 4]}
rscv = RandomizedSearchCV(dtc, params, scoring='accuracy', cv=5)
rscv.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(),
                   param_distributions={'max_leaf_nodes': [2, 3, 4, 5, 6, 7, 8,
                                                           9, 10, 11, 12, 13,
                                                           14, 15, 16, 17, 18,
                                                           19, 20, 21, 22, 23,
                                                           24, 25, 26, 27, 28,
                                                           29, 30, 31, ...],
                                        'min_samples_split': [2, 3, 4]},
                   scoring='accuracy')

In [130]:
dtc.fit(x_train, y_train)
y_predik = dtc.predict(x_test)

score_roc_auc = roc_auc_score(y_test, y_predik)
print('Score ROC_AUC (Decision Tree Clasiffier) : ', score_roc_auc)

Score ROC_AUC (Decision Tree Clasiffier) :  0.6197368421052631
